name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: RedSockActions/release_tag@v1.1.3
        with:
          token: ${{ github.token }}
          config_path: version/version.yaml